### ISSUE TITLE
Proxies setting doesn't work as expected for 7.0+

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1150]
### What happened?

I created a cluster with a different number of proxies than the default and the cluster was never able to reconcile. the cluster never reconciled with the error message that a configuration change is expected:

This was the result from the FDB status:

```json
{"redundancy_mode":"triple","storage_engine":"ssd-2","usable_regions":1,"logs":3,"proxies":30,"commit_proxies":26,"grv_proxies":4,"resolvers":1,"log_routers":-1,"remote_logs":-1}
```

This is what the operator expected:

```json
{"redundancy_mode":"triple","storage_engine":"ssd-2","usable_regions":1,"logs":3,"proxies":30,"commit_proxies":2,"grv_proxies":1,"resolvers":1,"log_routers":-1,"remote_logs":-1}}
```

### What did you expect to happen?

The cluster should be able to reconcile.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with the following spec:

```yaml
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: test-cluster
spec:
  processCounts:
    proxies: 30
  version: 7.1.0.-rc3
```

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
v1.1.1
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>
