### ISSUE TITLE
GRV and commit proxies are not working as expected

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1151]
### What happened?

I created a cluster with the following configuration:

```yaml
databaseConfiguration:
    commit_proxies: 26
    grv_proxies: 4
    redundancy_mode: triple
    storage_engine: ssd
```

The cluster never reconciled with the following error message:

```text
"current":{"redundancy_mode":"triple","storage_engine":"ssd-2","usable_regions":1,"logs":3,"proxies":3,"commit_proxies":2,"grv_proxies":1,"resolvers":1,"log_routers":-1,"remote_logs":-1}
"desired":{"redundancy_mode":"triple","storage_engine":"ssd-2","usable_regions":1,"logs":3,"proxies":3,"commit_proxies":26,"grv_proxies":4,"resolvers":1,"log_routers":-1,"remote_logs":-1}
```

### What did you expect to happen?

The cluster is properly configured and reconciles.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with the following config;

```yaml
databaseConfiguration:
    commit_proxies: 26
    grv_proxies: 4
    redundancy_mode: triple
    storage_engine: ssd
```

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
v1.1.1
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>
