### ISSUE TITLE
When overriding foundationdb-kubernetes-sidecar image on a backup CR, the tag is not correctly applied

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#1197]
### What happened?

I created a FoundationDBBackup resource as follows (irrevelant parts removed), to customize the image used for the sidecar:

```
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBBackup
metadata:
  name: my-fdb
spec:
  version: 6.3.22
  podTemplateSpec:
    spec:
      containers:
        - name: foundationdb
          image: myorg/foundationdb
        - name: foundationdb-kubernetes-sidecar
          image: myorg/foundationdb-kubernetes-sidecar:6.3.22-1
      initContainers:
        - name: foundationdb-kubernetes-init
          image: myorg/foundationdb-kubernetes-sidecar:6.3.22-1
          securityContext:
```

When I applied this, the operator errored, as follows:

```
"error":"image should not contain a tag but contains the tag \"6.3.22-1\"
```

If I _strip_ the tag (changing the image to simply `myorg/foundationdb-kubernetes-sidecar`, then the operator no longer errors, but the resulting backup-agent pods don't get the `6.3.22-1` tag automatically appended, and so kubernetes tries to pull `:latest` instead. Interestingly, the `6.3.22-1` tag _is_ correctly appended to the initContainer (_foundationdb-kubernetes-init_), but not to the pod container (_foundationdb-kubernetes-sidecar_).

### What did you expect to happen?

If we're going to rely on the operator to append the image tag to backup-agent pods (like it does with fdb pods), then this behavior should work consistently across both the initContainer and the container.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy fdb-operator 1.2.0 (I didn't upgrade yet because subsequent release notes don't mention this issue)
2. Deploy a minimal FoundationDBBackup CR as illustrated above
3. Observe the generated backup-agent pods

### Anything else we need to know?

This presents a problem for us because our policy is to whitelist specific tags/digests, and to avoid the use of `:latest` images.

### FDB Kubernetes operator

1.20

### Kubernetes version

1.22.9

### Cloud provider

Bare-metal, kubeadm-based.
