### ISSUE TITLE
Coordinator selection with processClass: coordinator results in 0 eligible candidates selection

### ISSUE THREAD

**Issue by iyuroch** [FoundationDB/fdb-kubernetes-operator#1244]
### What happened?

Foundationdbcluster with configuration
```
processCounts:
  coordinator: 5
coordinatorSelection:
  - processClass: coordinator
```
Result in an error that fdb-operator has 0 eligible candidates for coordinators.

### What did you expect to happen?

Coordinator elected from coordinator process class

### How can we reproduce it (as minimally and precisely as possible)?

Create cluster with 
```
processCounts:
  coordinator: 5
coordinatorSelection:
  - processClass: coordinator
```

### FDB Kubernetes operator

0.51.1

### Kubernetes version

1.22

### Cloud provider

AWS
