### ISSUE TITLE
Change crashLoop setup to allow to select container

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1438]
### What would you like to be added/changed?

The operator supports to add buggify to a running cluster e.g. by using `crashLoop`. We should adjust this setting (by creating a new setting and deprecate thee old one) to allow to select the container the struct could look like this:

```yaml
buggify:
  crashLoopContainer:
  - container: foundationdb
     targets:
     - storage-1
     - storage-2
  - container: foundationdb-kubernetes-sidecar
     targets:
     - storage-3
```

This allows to inject the crash loop behaviour into different containers.
