### ISSUE TITLE
Buggify crashloop no longer accepts '*' argument in the targets

### ISSUE THREAD

**Issue by JoshuaMcManus** [FoundationDB/fdb-kubernetes-operator#1777]
### What happened?

PR https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1667 changed the acceptable pattern for the crashloop container targets to only match formats of `storage-1`, but the field is also supposed to accept `*` for crash looping all processes. This is useful in the event of needing to force a failover by crashing all running pods in one of the regions in an HA configuration.

The CRD is defined in apps.foundationdb.org_foundationdbclusters.yaml:

```
buggify:
                properties:
                  blockRemoval:
                    items:
                      maxLength: 63
                      pattern: ^([\w-]+)-(\d+)$
                      type: string
                    maxItems: 1000
                    type: array
                  crashLoop:
                    items:
                      maxLength: 63
                      pattern: ^([\w-]+)-(\d+)$
                      type: string
                    type: array
                  crashLoopContainers:
                    items:
                      properties:
                        containerName:
                          maxLength: 253
                          minLength: 1
                          type: string
                        targets:
                          items:
                            maxLength: 63
                            pattern: ^([\w-]+)-(\d+)$
                            type: string
                          maxItems: 10000
                          minItems: 0
```

We should modify the regex to allow `*` to be accepted while also enforcing all other previous matchers.

### What did you expect to happen?

To be able to add the following to the cluster spec:

```
  spec:
    buggify:
      crashLoopContainers:
        - containerName: foundationdb
          targets:
            - '*'
```

And the cluster will trigger all pods into a crashloop.

### How can we reproduce it (as minimally and precisely as possible)?

Modify a cluster spec using the above changes.

### FDB Kubernetes operator

latest version

### Kubernetes version

n/a

### Cloud provider

n/a
