### ISSUE TITLE
Failing to get configmap when using --label-selector

### ISSUE THREAD

**Issue by gm42** [FoundationDB/fdb-kubernetes-operator#1953]
### What happened?

Creating any cluster with v1.33.0 fails with error:
```json
{
  "FoundationDBCluster": {
    "name": "mycluster",
    "namespace": "skunkworks"
  },
  "controller": "foundationdbcluster",
  "controllerGroup": "apps.foundationdb.org",
  "controllerKind": "FoundationDBCluster",
  "error": "configmaps \"mycluster-config\" already exists",
  "kubernetes": {
    "container_image": "foundationdb/fdb-kubernetes-operator:v1.33.0",
    "container_name": "manager",
    "pod_annotations": {
      "kubectl.kubernetes.io/restartedAt": "2024-02-27T22:42:29+01:00"
    },
    "pod_name": "fdb-operator-6bd85857d9-jtqww",
    "pod_namespace": "skunkworks",
  },
  "lvl": "error",
  "message": "Reconciler error",
  "name": "mycluster",
  "namespace": "skunkworks",
  "reconcileID": "3aee2109-3a13-4e50-9ac8-4450de6289ed",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:235",
  "stream": "stdout",
  "ts": "2024-02-28T13:44:19Z"
}
```

This is due to operator not finding the configmap (even if it exists), then attempting to create it and failing (because it exists).

This was introduced in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1922 because issue does not happen without this change.

### What did you expect to happen?

Cluster created correctly.

### How can we reproduce it (as minimally and precisely as possible)?

1. start operator with `--label-selector operator-only=yes` specified on the manager command line
2. `kubectl create -f mycluster.yaml` (any cluster definition will do, as far as the label is specified for it)
3. observe failure in operator logs

Example of how to specify the label:
```yaml
 kind: FoundationDBCluster
 metadata:
   name: mycluster
   labels:
     operator-only: "yes"
[...]
```

### Anything else we need to know?

Seems due to the special logic for label selector introduced in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1922

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
Error: deployments.apps "fdb-kubernetes-operator-controller-manager" not found
```
</details>

Not sure why this does not work, but I am using v1.33.0

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-77b1e4e", GitCommit:"c39acac7636499dd73442b62e11951592aedd1f8", GitTreeState:"clean", BuildDate:"2024-01-13T01:51:36Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

None

**Comment by johscheuer** [comment]
I see, that's probably a configuration issue. The resource labeling is documented here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/manual/customization.md#resource-labeling

Could you try to update your `FoundationDBCluster` Spec like this:

```yaml
kind: FoundationDBCluster
metadata:
 name: mycluster
 labels:
   operator-only: "yes"
spec:
  resourceLabels:
    foundationdb.org/fdb-cluster-name: mycluster
    operator-only: "yes" # <-- This is required to apply the label to all the created resources.
```

Please let me know if that fixed you issue. I will try to create an e2e test for this scenario either this or next week.
If you have any suggestion for better documentation, please let me know for create a PR with the improved documentation.

**Comment by gm42** [comment]
I think you meant like this:
```yaml
kind: FoundationDBCluster
metadata:
 name: mycluster
 labels:
   operator-only: "yes"
spec:
  labels:
    resourceLabels:
      operator-only: "yes"
```

Indeed this way it worked!

> If you have any suggestion for better documentation, please let me know for create a PR with the improved documentation.

I think [documentation](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/6a1ea6c10d5750ebff7d040a4c1d9c9f19cc6cb9/docs/manual/operations.md?plain=1#L116) is clear enough already, thanks!
