### ISSUE TITLE
Preferred pod antiaffinity can lead to coordinators in incorrect localities

### ISSUE THREAD

**Issue by gm42** [FoundationDB/fdb-kubernetes-operator#1959]
### What happened?

When enabling the fault domain feature the pods will have `podAntiAffinity` annotations which are preferred, this may lead to multiple coordinators scheduling on same nodes, which in turn leads to clusters which cannot be reconciled:
```
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Attempting to run sub-reconciler","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus"}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Disable taint feature","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus","Disabled":true}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Cluster does not have coordinators in the correct number of localities","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus","desiredCount":1,"currentCount":2,"locality":"ip-10-10-19-128.us-east-1.compute.internal"}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Cluster does not have coordinators in the correct number of localities","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus","desiredCount":1,"currentCount":3,"locality":"ip-10-20-42.127.us-east-1.compute.internal"}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Cluster has not enough running coordinators","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus","runningCoordinators":2,"desiredCount":5}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Pending coordinator change","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus","method":"CheckReconciliation","namespace":"skunkworks","cluster":"mycluster","state":"NeedsNewCoordinators"}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Subreconciler finished run","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.updateStatus","duration_seconds":0.120387471}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Cluster was not fully reconciled by reconciliation process","namespace":"skunkworks","cluster":"mycluster","status":{"needsCoordinatorChange":2},"CurrentGeneration":0,"OriginalGeneration":2,"DelayedRequeue":true}
{"level":"info","ts":"2024-02-19T13:50:09Z","logger":"controller","msg":"Reconciliation run finished","namespace":"skunkworks","cluster":"mycluster","duration_seconds":0.287201439,"cacheStatus":true}
```

### What did you expect to happen?

This is what operator is currently generating:
```yaml
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              foundationdb.org/fdb-cluster-name: mycluster
              foundationdb.org/fdb-process-class: coordinator
          topologyKey: kubernetes.io/hostname
        weight: 1
```

I expect operator to either use `requiredDuringSchedulingIgnoredDuringExecution` instead of `preferredDuringSchedulingIgnoredDuringExecution`, or to make the preferred/required configurable. Alternatively, I could specify my own `podAntiAffinity`.

### How can we reproduce it (as minimally and precisely as possible)?

Any cluster definition will do, if `podAntiAffinity` is not specified in the template:
```yaml
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: mycluster
  namespace: skunkworks
spec:
  version: 7.1.15
  faultDomain:
    key: kubernetes.io/hostname
    valueFrom: spec.nodeName
  coordinatorSelection:
  - priority: 100
    processClass: coordinator
  databaseConfiguration:
    logs: 1
    storage: 1
    redundancy_mode: single
    storage_engine: ssd-2
  processCounts:
    coordinator: 3
    stateless: 1
    storage: 1
    log: 1
```

### Anything else we need to know?

I was originally expecting to see topology spread constraints added, as it was mentioned [here](https://github.com/FoundationDB/fdb-kubernetes-operator/issues/875#issue-964763514), but then I found [this closed PR](https://github.com/FoundationDB/fdb-kubernetes-operator/issues/361) so I guess pod anti-affinity is the way to go for the time being.

The kubernetes scheduler may prefer scheduling on a certain node for example because volumes are already on that node.

### FDB Kubernetes operator

<details>
Cannot retrieve it via CLI but I am running v1.33.0
</details>

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-77b1e4e", GitCommit:"c39acac7636499dd73442b62e11951592aedd1f8", GitTreeState:"clean", BuildDate:"2024-01-13T01:51:36Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1

</details>

### Cloud provider

<details>

AWS

</details>
