### ISSUE TITLE
restart_delay custom parameter cannot be overridden (found duplicated customParameter)

### ISSUE THREAD

**Issue by gm42** [FoundationDB/fdb-kubernetes-operator#1973]
### What happened?

Trying to reduce the `restart_delay` fdbmonitor parameter leads to an operator error:
```
found the following customParameters violations:
found duplicated customParameter: restart_delay
```

### What did you expect to happen?

Some way to allow overriding the value of `restart_delay` from 60s to something else.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
processes:
    general:
      customParameters:
        - "restart_delay=5"
```

### FDB Kubernetes operator

<details>

v1.33.0
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-508b6b3", GitCommit:"ea12af9a627fef6922a0aa5fff59660ec8657d13", GitTreeState:"clean", BuildDate:"2024-01-29T21:00:01Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
k3d
</details>

**Comment by johscheuer** [comment]
Can you share the complete FoundationDBCluster resource? Setting a different `restart_delay` should already be supported based on the code. I just tested this with:

```yaml
  processes:
    general:
      customParameters:
      - restart_delay=5
      - trace_format=json
      podTemplate:
        metadata:
          annotations:
```

and that worked fine:

```text
[root@jdev-log-2 /]# cat /var/dynamic-conf/fdbmonitor.conf
[general]
kill_on_configuration_change = false
restart_delay = 60
[fdbserver.1]
command = /usr/bin/fdbserver
cluster_file = /var/fdb/data/fdb.cluster
seed_cluster_file = /var/dynamic-conf/fdb.cluster
public_address = ....:4500:tls
class = log
logdir = /var/log/fdb-trace-logs
loggroup = jscheuermann-jdev
datadir = /var/fdb/data
locality_instance_id = log-2
locality_machineid = jdev-log-2
locality_zoneid = jdev-log-2
listen_address = ....:4500:tls
restart_delay = 5
trace_format = json
```

Please provide the full details on how to reproduce this.

**Comment by gm42** [comment]
Sorry for the noise, I had actually specified it twice through some incorrect Helm replacement:
```yaml
  processes:
    general:
      customParameters:
      - restart_delay=5
      - restart_delay=5
      podTemplate:
        metadata:
          annotations:
```
