### ISSUE TITLE
Deferring reconciliation due to unsupported clients (coordinators)

### ISSUE THREAD

**Issue by gm42** [FoundationDB/fdb-kubernetes-operator#1991]
### What happened?

I run a cluster with separate coordinator pods which is using an older FoundationDB version e.g. `7.1.17`.
Once I set the version to latest `7.3.27`, operator never performs the upgrade because of this error:
```
{"level":"info","ts":"2024-04-16T06:22:20Z","logger":"controller","msg":"Reconciliation terminated early","namespace":"skunkworks","cluster":"mycluster","reconciler":"controllers.checkClientCompatibility","requeueAfter":60,"message":"7 clients do not support version 7.3.27: 192.168.149.171:49018, 192.168.149.171:52564, 192.168.159.185:52772, 192.168.159.185:55498, 192.168.190.37:36264, 192.168.190.37:42684, 192.168.190.37:52468"}
```

However those IPs correspond to the pod IPs of 3 of the coordinators (!), not an external client (from cluster PoV).

### What did you expect to happen?

Operator carrying out the update by pod replacement, not considering connections from coordinators as blocking.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster:
```yaml
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: mycluster
  namespace: skunkworks
spec:
  version: 7.1.17
  routing:
    publicIPSource: service
  coordinatorSelection:
  - priority: 100
    processClass: coordinator
  databaseConfiguration:
    logs: 3
    storage: 3
    redundancy_mode: single
    storage_engine: ssd-2
  processCounts:
    coordinator: 3
    stateless: 3
    storage: 3
    log: 3
```

Start using it using some other client, so that there is some activity on it; then change its version to `7.3.27` using `kubectl edit`.

### FDB Kubernetes operator

<details>
v1.33
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.14-eks-b9c9ed7
```

</details>

### Cloud provider

<details>
AWS
</details>
