### ISSUE TITLE
Deleted Pods are not recreated

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#315]
I used the following spec to create a local FDB cluster for testing purpose:

```yaml
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  name: sample-cluster
spec:
  version: 6.2.25
  processes:
    general:
      podTemplate:
        spec:
          containers:
          - name: foundationdb
            resources:
              requests:
                cpu: 250m
                memory: 128Mi
      volumeClaim:
        spec:
          resources:
            requests:
              storage: "8G"
```

Everything comes up fine:

```bash
$ kubectl get po
NAME                                                          READY   STATUS    RESTARTS   AGE
fdb-kubernetes-operator-controller-manager-645f6b9dd6-r4zpm   1/1     Running   0          30m
sample-cluster-log-1                                          2/2     Running   0          7m22s
sample-cluster-log-2                                          2/2     Running   0          7m22s
sample-cluster-log-3                                          2/2     Running   0          7m22s
sample-cluster-log-4                                          2/2     Running   0          7m22s
sample-cluster-stateless-1                                    2/2     Running   0          7m23s
sample-cluster-stateless-2                                    2/2     Running   0          7m23s
sample-cluster-stateless-3                                    2/2     Running   0          7m23s
sample-cluster-stateless-4                                    2/2     Running   0          7m23s
sample-cluster-stateless-5                                    2/2     Running   0          7m23s
sample-cluster-stateless-6                                    2/2     Running   0          7m22s
sample-cluster-stateless-7                                    2/2     Running   0          7m22s
sample-cluster-stateless-8                                    2/2     Running   0          7m22s
sample-cluster-stateless-9                                    2/2     Running   0          7m22s
sample-cluster-storage-1                                      2/2     Running   0          7m23s
sample-cluster-storage-2                                      2/2     Running   0          7m23s
sample-cluster-storage-3                                      2/2     Running   0          7m23s

$  kubectl get fdb
NAME             GENERATION   RECONCILED   HEALTHY
sample-cluster   1            1            true
```

In the next step I just delete all Pods of the cluster: `kubectl delete po -l fdb-cluster-name=sample-cluster` and now all Pods are gone (as expected). But I would expect that the operator recreates Pods that are deleted, at least I couldn't find any information in the docs that the operator shouldn't recreate them.

Fun fact the operator still thinks the cluster is healthy:

```bash 
$  kubectl get fdb
NAME             GENERATION   RECONCILED   HEALTHY
sample-cluster   1            1            true
```

Is this just a limitation that should be documented or should the operator actually recreate Pods if they get deleted?

edit: This is actually a challenge if one of the nodes are drained with `kubectl drain ...` for maintenance reason because the drained Pod(s) won't be recreated.
