### ISSUE TITLE
Create design to prevent user to remove to many Pods

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#316]
When thinking about https://github.com/FoundationDB/fdb-kubernetes-operator/issues/315 I came across the issue that the complete cluster was offline (obviously this was a test case) which could happen if a (human) operator has some fat fingers. We should optionally add `PodDIsruptionbudget` for the Pod groups to ensure that the cluster stays available even if someone would try to delete all Pods, see: https://kubernetes.io/docs/tasks/run-application/configure-pdb.

**Comment by rbtcollins** [comment]
(Copied my detail from the dup I filed) - this is much larger than just fat fingers: it has implications on cluster upgrades, node autoscalers, horizontal pod autoscalers in future as well.

Foundation DB requires that a certain number of pods are running to retain quorum; Kubernetes supports not deliberately disrupting those pods if an API object called a PodDisruptionBudget is created in the same namespace as the pods, with a selector that matches the pods in question.

This gets a little tricky because of recruitment - unless it is possible to restrict the coordinator role to a subset of processes (is it?), we need to prevent disrupting (quorum-1) *processes* across all processes; and this needs to take into account the design for multi-storage-pods, which is on my todo to review (does that correctly provide anti-affinity for coordinators?). 

What happens to a cluster if all coordinators are killed atomically, even though the rest of the processes are live?

Anyhow, PDB's, great things, lets write one:

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{fdb-clustername}}
spec:
  minAvailable: {{nodecount-2}}
  selector:
    matchLabels:
      fdbcluster: {{fdb-clustername}}
```
