### ISSUE TITLE
Specifying a sidecar container image with tag results in an invalid config

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#342]
I used this cluster config for testing the sidecar with some custom changes:

```yaml
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  name: sample-cluster
  labels:
    test: jscheuermann
spec:
  version: 6.2.25
  updatePodsByReplacement: true
  services:
    headless: true
  processes:
    general:
      podTemplate:
        spec:
          containers:
          - name: foundationdb
            resources:
              requests:
                cpu: 250m
                memory: 128Mi
          - name: foundationdb-kubernetes-sidecar
            image: johscheuer/foundationdb-kubernetes-sidecar:6.2.25-1-slim
      volumeClaim:
        spec:
          resources:
            requests:
              storage: "10G"
```

The result was an invalid image:

```bash
 Warning  InspectFailed  9s (x2 over 10s)  kubelet            Failed to apply default image tag "johscheuer/foundationdb-kubernetes-sidecar:6.2.25-1-slim:6.2.25-1": couldn't parse image reference "johscheuer/foundationdb-kubernetes-sidecar:6.2.25-1-slim:6.2.25-1": invalid reference format
```

IMHO if the specified image already contains a tag the operator should not add an additional tag.
