### ISSUE TITLE
Feature request: pod disruption budgets

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#354]
Missed this in my first pass of functionality - sorry for the delay! (Also moved countries during Covid in the middle).

Anyway - Foundation DB requires that a certain number of pods are running to retain quorum; Kubernetes supports not deliberately disrupting those pods if an API object called a PodDisruptionBudget is created in the same namespace as the pods, with a selector that matches the pods in question.

This gets a little tricky because of recruitment - unless it is possible to restrict the coordinator role to a subset of processes (is it?), we need to prevent disrupting (quorum-1) *processes* across all processes; and this needs to take into account the design for multi-storage-pods, which is on my todo to review (does that correctly provide anti-affinity for coordinators?). 

What happens to a cluster if all coordinators are killed atomically, even though the rest of the processes are live?

Anyhow, PDB's, great things, lets write one:

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{fdb-clustername}}
spec:
  minAvailable: {{nodecount-2}}
  selector:
    matchLabels:
      fdbcluster: {{fdb-clustername}}
```
