### ISSUE TITLE
Document example client with TLS cluster

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#415]
We should provide an example how to connect to a TLS enabled FDB cluster in the samples/docs.

**Comment by tahuy** [comment]
Hi @johscheuer 
Do you have any example about FDB Java API connect to TLS FDB cluster?

**Comment by johscheuer** [comment]
Hi,

You just have to mount the TLS certificates in the container and then set he TLS variables:

```yaml
    - name: FDB_TLS_CERTIFICATE_FILE
      value: /tmp/fdb-certs/tls.crt
    - name: FDB_TLS_CA_FILE
      value: /tmp/fdb-certs/tls.crt
    - name: FDB_TLS_KEY_FILE
      value: /tmp/fdb-certs/tls.key
```

That should be everything.
