### ISSUE TITLE
Bug: readOnlyRootFilesystem is not overwritten

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#602]
I currently have the following FDB Spec:

```yaml
  processes:
    general:
      podTemplate:
        spec:
          containers:
          - name: foundationdb
            securityContext:
              readOnlyRootFilesystem: false
    storage:
      allowTagOverride: false
      customParameters:
      - knob_report_dd_metrics=0
```

and I also tried:

```yaml
  processes:
    general:
      podTemplate:
        spec:
          containers:
          - name: foundationdb
            securityContext:
              readOnlyRootFilesystem: false
    storage:
      allowTagOverride: false
      customParameters:
      - knob_report_dd_metrics=0
      podTemplate:
        spec:
          containers:
          - name: foundationdb
            securityContext:
              readOnlyRootFilesystem: false
```

I would expect that `readOnlyRootFilesystem` is set to `false` but the created pods have the field set to `true`:

```yaml
  containers:
  - name: foundationdb
    securityContext:
      readOnlyRootFilesystem: true
```

I assume that this is a bug somewhere in the merge process.
