### ISSUE TITLE
customParameters should be merged together

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#636]
I tried to use this modified sample cluster spec  (I removed the default fields):

```yaml
processes:
    general:
      customParameters:
        - "locality_test=1"
        - "trace_format=json"
    storage:
      customParameters:
        - "knob_disable_posix_kernel_aio=1"
```

I would expect that the `customParameters` are merged and all storage processes will have all 3 custom parameters but only the most specific list of `customParameters` will be used e.g. in my case only `knob_disable_posix_kernel_aio=1` will be set. This is the resulting `fdbmonitor.conf`:

```bash
root@sample-cluster-storage-4:/var/fdb# cat /var/dynamic-conf/fdbmonitor.conf
[general]
kill_on_configuration_change = false
restart_delay = 60
[fdbserver.1]
command = /usr/bin/fdbserver
cluster_file = /var/fdb/data/fdb.cluster
seed_cluster_file = /var/dynamic-conf/fdb.cluster
public_address = 10.1.8.225:4501
class = storage
logdir = /var/log/fdb-trace-logs
loggroup = sample-cluster
datadir = /var/fdb/data
locality_instance_id = storage-4
locality_machineid = sample-cluster-storage-4
locality_zoneid = sample-cluster-storage-4
knob_disable_posix_kernel_aio=1
```

I think it will be useful to merge the `customParameters` and actually that would be something that I expect.
