### ISSUE TITLE
Document FDB operator requirements fro TLS 

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#710]
We should document in our [user manual](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/user_manual.md) the requirements for a TLS cluster setup. Currently users are not aware of the fact that they have to set the env variables and secret mount for the [operator](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/v0.35.0/controllers/pod_client.go#L86-L129):

```yaml
                env:
                  - name: FDB_TLS_CERTIFICATE_FILE
                    value: /tmp/fdb-certs/tls.crt
                  - name: FDB_TLS_CA_FILE
                    value: /tmp/fdb-certs/tls.crt
                  - name: FDB_TLS_KEY_FILE
                    value: /tmp/fdb-certs/tls.key
```

The error message is shown in: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/709 and we should probably think of printing out a more concrete error message e.g. `operator Pod is missing ...`.
