### ISSUE TITLE
Operator stuck on "cannot find enough pods to recruit coordinators" in triple redundancy mode since 0.37.0

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#839]
Hey guys!

On v0.38.0 (and 0.37.0) I've not been able to get my cluster to reconcile when I use triple redundancy mode.

Here's my CR:

```
spec:
  databaseConfiguration:
    redundancy_mode: triple
    storage: 4
  processCounts:
    cluster_controller: -1
    log: -1
    stateless: -1
```

The 4 pods are created within about 30s, but the operator continually logs:

```
{"level":"info","ts":1625871790.9355466,"logger":"controller","msg":"Reconciliation terminated early","namespace":"prod","cluster":"retort-fdb","subReconciler":"controllers.GenerateInitialClusterFile","message":"cannot find enough pods to recruit coordinators","requeueAfter":15}
```

As soon as I change `redunancy_mode` to `double`, the operator reconciles the cluster.

My reading of https://apple.github.io/foundationdb/configuration.html#configuration-choosing-redundancy-mode indicates that 4 machines should be a supported configuration for triple redundancy mode. To be sure, I also tried `storage: 5`, but the same behaviour resulted.

I've previously had triple redundancy mode working with this cluster configuration on 0.36.0.

Thanks!
D
