### ISSUE TITLE
Using a PodNodeSelector causes endless pods to be created

### ISSUE THREAD

**Issue by benzim** [FoundationDB/fdb-kubernetes-operator#950]
[This change](https://github.com/FoundationDB/fdb-kubernetes-operator/pull/467) to replace a pod when the nodeSelector is changed is causing the operator to create pods infinitely if a [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector) is present. This is because the PodNodeSelector applies a nodeSelector to every pod before it is deployed so when the operator checks if the nodeSelector for the deployed pod matches the nodeSelector in the pod template they don't match. This causes the operator to mark every pod for replacement and create new pods which then also have a nodeSelector applied by the PodNodeSelector.

Steps to reproduce:
1. Create a namespace with the `scheduler.alpha.kubernetes.io/node-selector` annotation like the one below.
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/worker=
  name: test-namespace
```
2. Deploy the operator and FoundationDBCluster to the namespace.
3. Operator keeps creating pods.

Is this something that could be fixed or will the user have to make sure that the nodeSelector in the FoundationDBCluster pod template matches the PodNodeSelector?
